version: '3'
services:
    cabinet:
        container_name: cabinet
        build:
            context: .
            dockerfile: Dockerfile
        image: cabinet:latest
        ports:
            - 18081:18081
        volumes:
          - ${HOST_PATH}:/usr/local/cabinet/
        # networks:
        #     - spring-cloud-network
    # product-server:
    #     container_name: product-server
    #     build:
    #         context: docker-product-server
    #         dockerfile: Dockerfile
    #     image: product-server:latest
    #     ports:
    #         - 19999:9999
    #     networks:
    #         - spring-cloud-network
# networks:
#     spring-cloud-network:
#         driver: bridge